// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZsaTVORS8KS7OB4Znz_D5s_kdOPCdKg',
    appId: '1:333509303385:web:06e517b789a663ae9c6548',
    messagingSenderId: '333509303385',
    projectId: 'bma-flutter-firebase',
    authDomain: 'bma-flutter-firebase.firebaseapp.com',
    storageBucket: 'bma-flutter-firebase.appspot.com',
    measurementId: 'G-JNYCHHP3LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaY6fkSfPAXQK4_yZCR8o6nozkN42YCbY',
    appId: '1:333509303385:android:e5d989546abdc3f49c6548',
    messagingSenderId: '333509303385',
    projectId: 'bma-flutter-firebase',
    storageBucket: 'bma-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVLQIzMsOx52p3JzDqw7gq88EXKPE1vQ',
    appId: '1:333509303385:ios:56d8b7f784c8479c9c6548',
    messagingSenderId: '333509303385',
    projectId: 'bma-flutter-firebase',
    storageBucket: 'bma-flutter-firebase.appspot.com',
    iosBundleId: 'com.example.bma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeVLQIzMsOx52p3JzDqw7gq88EXKPE1vQ',
    appId: '1:333509303385:ios:56d8b7f784c8479c9c6548',
    messagingSenderId: '333509303385',
    projectId: 'bma-flutter-firebase',
    storageBucket: 'bma-flutter-firebase.appspot.com',
    iosBundleId: 'com.example.bma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZZsaTVORS8KS7OB4Znz_D5s_kdOPCdKg',
    appId: '1:333509303385:web:b1ab03e17b187fcc9c6548',
    messagingSenderId: '333509303385',
    projectId: 'bma-flutter-firebase',
    authDomain: 'bma-flutter-firebase.firebaseapp.com',
    storageBucket: 'bma-flutter-firebase.appspot.com',
    measurementId: 'G-5ZGBE7RMH1',
  );
}
